export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const LOAD_MORE_PRODUCTS_START = 'LOAD_MORE_PRODUCTS_START';
export const LOAD_MORE_PRODUCTS_SUCCESS = 'LOAD_MORE_PRODUCTS_SUCCESS';
export const LOAD_MORE_PRODUCTS_FAILURE = 'LOAD_MORE_PRODUCTS_FAILURE';

// export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START';
// export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
// export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';

export const FETCH_FAMILIES_START = 'FETCH_FAMILIES_START';
export const FETCH_FAMILIES_SUCCESS = 'FETCH_FAMILIES_SUCCESS';
export const FETCH_FAMILIES_FAILURE = 'FETCH_FAMILIES_FAILURE';

export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const CLEAN_CART = 'CLEAN_CART';
