export const FETCH_SERVER_START = 'FETCH_SERVER_START'
export const FETCH_SERVER_SUCCESS = 'FETCH_SERVER_SUCCESS'
export const FETCH_SERVER_FAILURE = 'FETCH_SERVER_FAILURE'

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'

export const LOAD_MORE_PRODUCT_START = 'LOAD_MORE_PRODUCT_START'
export const LOAD_MORE_PRODUCT_SUCCESS = 'LOAD_MORE_PRODUCT_SUCCESS'
export const LOAD_MORE_PRODUCT_FAILURE = 'LOAD_MORE_PRODUCT_FAILURE'

export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START'
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS'
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'

export const FETCH_FAMILIES_START = 'FETCH_FAMILIES_START'
export const FETCH_FAMILIES_SUCCESS = 'FETCH_FAMILIES_SUCCESS'
export const FETCH_FAMILIES_FAILURE = 'FETCH_FAMILIES_FAILURE'

export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'

export const CLEAN_CART = 'CLEAN_CART'

